version: '3.8'

services:
  db:
    image: postgres:15.3
    container_name: app-db
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis/redis-stack:latest
    container_name: app-redis
    ports:
      - 6379:6379
      - 8001:8001
    restart: always
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: