version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app-api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db

  db:
    image: postgres:15.3
    container_name: app-db
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_pass
      POSTGRES_DB: app_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: